CREATE TABLE IF NOT EXISTS "task_lists" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "order" TEXT
);

CREATE INDEX "ix_task_lists_index" ON "task_lists" ("index");

CREATE TABLE IF NOT EXISTS "tasks" (
    "index" INTEGER,
    "id" TEXT,
    "label" TEXT,
    "section" TEXT,
    "section_order" TEXT,
    "task_order" TEXT,
    "task_list_id" TEXT
);

CREATE INDEX "ix_tasks_index" ON "tasks" ("index");

CREATE TABLE IF NOT EXISTS "charts_of_accounts" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "accounting_integration_service_id" TEXT,
    "discount_account_id" TEXT,
    "receivables_account_id" TEXT,
    "tax_account_id" TEXT,
    "tax_item_id" TEXT,
    "valid_configuration" TEXT,
    "export_payments" TEXT,
    "refund_account_id" TEXT,
    "collect_tax" TEXT,
    "deprecated_accounting_payer_as_customer" TEXT,
    "track_line_item_classes" TEXT,
    "aggregate_package_discounts" TEXT,
    "qbd_send_tax" TEXT,
    "qbo_line_item_refunds" TEXT,
    "package_discounts_applied_before_tax" TEXT,
    "customer_export_name_src" TEXT,
    "customer_export_address_src" TEXT,
    "soa_use_expanding_interests" TEXT,
    "sfgs_show_interests_line_item" TEXT,
    "show_deceased_name" TEXT,
    "non_tax_item_id_klass" TEXT
);

CREATE INDEX "ix_charts_of_accounts_index" ON "charts_of_accounts" ("index");

CREATE TABLE IF NOT EXISTS "accounts" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "deprecated_account_type" TEXT,
    "chart_of_accounts_id" TEXT,
    "autogenerated" TEXT,
    "account_type" TEXT,
    "remote_id" TEXT,
    "general_ledger_id" TEXT
);

CREATE INDEX "ix_accounts_index" ON "accounts" ("index");

CREATE TABLE IF NOT EXISTS "tax_items" (
    "index" INTEGER,
    "id" TEXT,
    "chart_of_accounts_id" TEXT,
    "name" TEXT,
    "description" TEXT
);

CREATE INDEX "ix_tax_items_index" ON "tax_items" ("index");

CREATE TABLE IF NOT EXISTS "special_taxes" ("index" TEXT);

CREATE INDEX "ix_special_taxes_index" ON "special_taxes" ("index");

CREATE TABLE IF NOT EXISTS "payment_types" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "account_id" TEXT,
    "process_credit_card" TEXT,
    "chart_of_accounts_id" TEXT,
    "collect_check_number" TEXT,
    "collect_cc_last_four" TEXT,
    "associate_insurance_policy" TEXT,
    "is_tribute_pay" TEXT,
    "integration_service_id_klass" TEXT
);

CREATE INDEX "ix_payment_types_index" ON "payment_types" ("index");

CREATE TABLE IF NOT EXISTS "adjustment_types" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "gain" TEXT,
    "account_id" TEXT,
    "chart_of_accounts_id" TEXT,
    "is_tribute_pay_fee" TEXT,
    "integration_service_id_klass" TEXT
);

CREATE INDEX "ix_adjustment_types_index" ON "adjustment_types" ("index");

CREATE TABLE IF NOT EXISTS "discount_types" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "taxable" TEXT,
    "chart_of_accounts_id" TEXT,
    "account_id" TEXT,
    "archived_at" TEXT
);

CREATE INDEX "ix_discount_types_index" ON "discount_types" ("index");

CREATE TABLE IF NOT EXISTS "general_price_lists" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "chart_of_accounts_id" TEXT
);

CREATE INDEX "ix_general_price_lists_index" ON "general_price_lists" ("index");

CREATE TABLE IF NOT EXISTS "product_categories" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "account_id" TEXT,
    "general_price_list_id" TEXT,
    "uuid" TEXT,
    "asset_account_id_klass" TEXT,
    "cogs_account_id_klass" TEXT,
    "preneed_category_id_klass" TEXT,
    "cogs_account_id" TEXT,
    "asset_account_id" TEXT,
    "archived_at" TEXT
);

CREATE INDEX "ix_product_categories_index" ON "product_categories" ("index");

CREATE TABLE IF NOT EXISTS "statement_categories" ("index" TEXT);

CREATE INDEX "ix_statement_categories_index" ON "statement_categories" ("index");

CREATE TABLE IF NOT EXISTS "statement_subcategories" ("index" TEXT);

CREATE INDEX "ix_statement_subcategories_index" ON "statement_subcategories" ("index");

CREATE TABLE IF NOT EXISTS "products" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "price" TEXT,
    "is_taxed" TEXT,
    "product_category_id" TEXT,
    "is_customizable" TEXT,
    "cost" TEXT,
    "state_tax" TEXT,
    "local_tax" TEXT,
    "tracking" TEXT,
    "has_special_tax" TEXT,
    "is_export_cogs" TEXT,
    "general_price_list_id" TEXT,
    "is_discretionary" TEXT,
    "include_shipping" TEXT,
    "shipping_total" TEXT,
    "uuid" TEXT,
    "invoice_category_id_klass" TEXT,
    "statement_category_id_klass" TEXT,
    "statement_subcategory_id_klass" TEXT,
    "special_tax_id_klass" TEXT,
    "invoice_category_name" TEXT,
    "archived_at" TEXT,
    "short_description" TEXT,
    "description" TEXT
);

CREATE INDEX "ix_products_index" ON "products" ("index");

CREATE TABLE IF NOT EXISTS "packages" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "pricing_amount" TEXT,
    "pricing_method" TEXT,
    "archived_at" TEXT,
    "is_customizable" TEXT,
    "general_price_list_id" TEXT,
    "qbo_discount_id" TEXT,
    "is_discretionary" TEXT,
    "invoice_category_id_klass" TEXT,
    "invoice_category_name" TEXT,
    "description" TEXT
);

CREATE INDEX "ix_packages_index" ON "packages" ("index");

CREATE TABLE IF NOT EXISTS "package_products" (
    "index" INTEGER,
    "package_id" TEXT,
    "product_id" TEXT,
    "id" TEXT
);

CREATE INDEX "ix_package_products_index" ON "package_products" ("index");

CREATE TABLE IF NOT EXISTS "locations" (
    "index" INTEGER,
    "id" TEXT,
    "address_id" TEXT,
    "phone_number" TEXT,
    "website_url" TEXT,
    "color" TEXT,
    "current_state_sales_tax_rate" TEXT,
    "current_local_sales_tax_rate" TEXT,
    "general_price_list_id" TEXT,
    "owner" TEXT,
    "kase_numbering_format" TEXT,
    "kase_numbering_resets_yearly" TEXT,
    "kase_numbering_resets_monthly" TEXT,
    "guid" TEXT,
    "default_contract_template_id" TEXT,
    "default_crem_auth_header_id_klass" TEXT,
    "default_receipt_logo_id_klass" TEXT,
    "default_sfgs_logo_id_klass" TEXT,
    "default_soa_logo_id_klass" TEXT,
    "managing_director_id_klass" TEXT
);

CREATE INDEX "ix_locations_index" ON "locations" ("index");

CREATE TABLE IF NOT EXISTS "addresses" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "line1" TEXT,
    "line2" TEXT,
    "city" TEXT,
    "county" TEXT,
    "state" TEXT,
    "zip_code" TEXT,
    "country" TEXT,
    "uuid" TEXT,
    "township" TEXT,
    "latitude" TEXT,
    "longitude" TEXT,
    "fax_number" TEXT
);

CREATE INDEX "ix_addresses_index" ON "addresses" ("index");

CREATE TABLE IF NOT EXISTS "places" (
    "index" INTEGER,
    "id" TEXT,
    "address_id" TEXT,
    "uuid" TEXT,
    "is_vendor" TEXT,
    "phone_number" TEXT,
    "fax_number" TEXT,
    "notes" TEXT,
    "website_url" TEXT,
    "archived_at" TEXT,
    "email" TEXT
);

CREATE INDEX "ix_places_index" ON "places" ("index");

CREATE TABLE IF NOT EXISTS "profiles" (
    "index" INTEGER,
    "id" TEXT,
    "personal_info_is_complete" TEXT,
    "death_info_is_complete" TEXT,
    "contact_info_is_complete" TEXT,
    "birth_info_is_complete" TEXT,
    "fetal_death" TEXT,
    "place_of_death_id_klass" TEXT,
    "place_of_death_area" TEXT,
    "place_of_death_id" TEXT,
    "death_time" TEXT,
    "death_date" TEXT,
    "archived_at" TEXT,
    "death_inside_city_limits" TEXT,
    "found" TEXT,
    "death_circumstances" TEXT,
    "presumed_death_time" TEXT,
    "manner_of_death" TEXT
);

CREATE INDEX "ix_profiles_index" ON "profiles" ("index");

CREATE TABLE IF NOT EXISTS "users" (
    "index" INTEGER,
    "id" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "mobile" TEXT,
    "email" TEXT,
    "middle_name" TEXT,
    "funeral_director_license_number" TEXT
);

CREATE INDEX "ix_users_index" ON "users" ("index");

CREATE TABLE IF NOT EXISTS "people" (
    "index" INTEGER,
    "id" TEXT,
    "first_name" TEXT,
    "phone_primary" TEXT,
    "phone_secondary" TEXT,
    "gender" TEXT,
    "occupation" TEXT,
    "country" TEXT,
    "uuid" TEXT,
    "birthplace_id_klass" TEXT,
    "mailing_address_id_klass" TEXT,
    "kase_id_klass" TEXT,
    "profile_id_klass" TEXT,
    "last_name" TEXT,
    "email" TEXT,
    "address_line1" TEXT,
    "city" TEXT,
    "state" TEXT,
    "zip_code" TEXT,
    "middle_name" TEXT,
    "hispanic" TEXT,
    "county" TEXT,
    "inside_city_limits" TEXT,
    "social_security_number" TEXT,
    "kase_id" TEXT,
    "birth_date" TEXT,
    "birthplace_id" TEXT,
    "profile_id" TEXT,
    "marital_status" TEXT,
    "race" TEXT,
    "mailing_address_id" TEXT,
    "address_line2" TEXT,
    "name_suffix" TEXT,
    "maiden_name" TEXT,
    "township" TEXT,
    "industry" TEXT,
    "education" TEXT,
    "hispanic_origin" TEXT,
    "ancestry" TEXT,
    "interests_or_achievements" TEXT,
    "years_in_occupation" TEXT,
    "retired" TEXT,
    "name_prefix" TEXT,
    "alt_name_1" TEXT,
    "alt_name_2" TEXT,
    "notes" TEXT,
    "printed_name" TEXT,
    "religion" TEXT,
    "email_secondary" TEXT,
    "borough" TEXT,
    "employer" TEXT,
    "church" TEXT,
    "employer_years" TEXT,
    "fax_number" TEXT,
    "language" TEXT,
    "organizations_or_memberships" TEXT,
    "archived_at" TEXT,
    "race_other" TEXT,
    "spouse_first_name" TEXT,
    "spouse_last_name" TEXT,
    "contact_age" TEXT,
    "license_number" TEXT,
    "spouse_middle_name" TEXT,
    "spouse_maiden_name" TEXT
);

CREATE INDEX "ix_people_index" ON "people" ("index");

CREATE TABLE IF NOT EXISTS "cases" (
    "index" INTEGER,
    "id" TEXT,
    "is_coroners_kase" TEXT,
    "is_organ_donor" TEXT,
    "is_autopsy_after_donation" TEXT,
    "permission_to_transfer" TEXT,
    "had_autopsy" TEXT,
    "released_for_pickup" TEXT,
    "is_coroner_notified" TEXT,
    "is_body_donation" TEXT,
    "is_veteran" TEXT,
    "has_permission_to_embalm" TEXT,
    "location_id" TEXT,
    "trade_call" TEXT,
    "custom_id" TEXT,
    "status" TEXT,
    "export" TEXT,
    "mother_id" TEXT,
    "father_id" TEXT,
    "spouse_id" TEXT,
    "decline_embalming" TEXT,
    "ship_in" TEXT,
    "is_examiner_investigator_case" TEXT,
    "positively_identified" TEXT,
    "casketing_and_cosmetics" TEXT,
    "transport_to_crematory" TEXT,
    "paid_in_full" TEXT,
    "has_kase_forms" TEXT,
    "general_price_list_locked" TEXT,
    "general_price_list_id" TEXT,
    "hide_on_dashboard" TEXT,
    "informant_relationship" TEXT,
    "location_locked" TEXT,
    "deprecated_pacemaker" TEXT,
    "permission_to_photograph" TEXT,
    "permission_to_fingerprint" TEXT,
    "corona_virus_warning" TEXT,
    "has_chain_of_custody" TEXT,
    "uuid" TEXT,
    "has_no_events" TEXT,
    "is_pregnant" TEXT,
    "is_tobacco_related" TEXT,
    "is_alcohol_related" TEXT,
    "is_findings_available" TEXT,
    "is_hidden_from_whiteboard" TEXT,
    "has_implanted_devices" TEXT,
    "has_kase_cause_of_death" TEXT,
    "body_donation_place_id_klass" TEXT,
    "cemetery_id_klass" TEXT,
    "created_by_user_id_klass" TEXT,
    "identification_place_id_klass" TEXT,
    "embalming_place_id_klass" TEXT,
    "place_id_klass" TEXT,
    "marriage_place_id_klass" TEXT,
    "trade_call_place_id_klass" TEXT,
    "transport_to_location_id_klass" TEXT,
    "vendor_id_klass" TEXT,
    "body_donation_contact_id_klass" TEXT,
    "next_of_kin_id_klass" TEXT,
    "primary_contact_id_klass" TEXT,
    "ship_in_contact_id_klass" TEXT,
    "ship_in_pickup_id_klass" TEXT,
    "trade_call_contact_id_klass" TEXT,
    "trade_call_pickup_id_klass" TEXT,
    "reason_to_embalm" TEXT,
    "created_by_user_id" TEXT,
    "father_id_klass" TEXT,
    "mother_id_klass" TEXT,
    "spouse_id_klass" TEXT,
    "is_injury_related" TEXT,
    "is_work_injury" TEXT,
    "primary_contact_id" TEXT,
    "next_of_kin_id" TEXT,
    "marriage_date" TEXT,
    "asd_exported_at" TEXT,
    "transport_to_location_id" TEXT,
    "removal_pickup_time" TEXT,
    "kase_numbering_format" TEXT,
    "kase_numbering_preformat" TEXT,
    "kase_numbering_identifier" TEXT,
    "kase_numbering_generated_at" TEXT,
    "preneed_to_atneed_at" TEXT,
    "pickup_phone" TEXT,
    "pickup_instructions" TEXT,
    "general_price_list_id_klass" TEXT,
    "location_id_klass" TEXT,
    "exported_at" TEXT,
    "weight" TEXT,
    "pacemaker_detail" TEXT,
    "special_circumstances" TEXT,
    "body_donation_place_id" TEXT,
    "organ_donation_type" TEXT,
    "embalming_date" TEXT,
    "trade_call_contact_id" TEXT,
    "trade_call_place_id" TEXT,
    "crematory_transport_time" TEXT,
    "preneed_case_id" TEXT,
    "height" TEXT,
    "embalm_authorization_date" TEXT,
    "embalming_place_id" TEXT,
    "deceased_tag_number" TEXT,
    "jewelry" TEXT,
    "casket" TEXT,
    "date_casket_ordered" TEXT,
    "date_casket_delivered" TEXT,
    "citizenship" TEXT,
    "identification_date" TEXT,
    "identification_place_id" TEXT,
    "investigation_number" TEXT,
    "trade_call_organization_name" TEXT,
    "body_donation_notes" TEXT,
    "fingerprint_reason" TEXT,
    "glasses" TEXT,
    "clothing" TEXT,
    "marriage_place_id" TEXT
);

CREATE INDEX "ix_cases_index" ON "cases" ("index");

CREATE TABLE IF NOT EXISTS "notes" (
    "index" INTEGER,
    "id" TEXT,
    "user_id" TEXT,
    "kase_id" TEXT,
    "content" TEXT,
    "requires_follow_up" TEXT,
    "user_id_klass" TEXT
);

CREATE INDEX "ix_notes_index" ON "notes" ("index");

CREATE TABLE IF NOT EXISTS "relatives" (
    "index" INTEGER,
    "id" TEXT,
    "person_id" TEXT,
    "decedent_id" TEXT,
    "relationship_name" TEXT
);

CREATE INDEX "ix_relatives_index" ON "relatives" ("index");

CREATE TABLE IF NOT EXISTS "case_contacts" (
    "index" INTEGER,
    "id" TEXT,
    "relative_id" TEXT,
    "kase_id" TEXT
);

CREATE INDEX "ix_case_contacts_index" ON "case_contacts" ("index");

CREATE TABLE IF NOT EXISTS "case_people" (
    "index" INTEGER,
    "id" TEXT,
    "person_id" TEXT,
    "kase_id" TEXT,
    "doctor" TEXT,
    "death_certifier" TEXT,
    "informant" TEXT,
    "clergy" TEXT,
    "policy_owner" TEXT,
    "secondary_clergy" TEXT,
    "remains_pickup_person" TEXT,
    "pallbearer" TEXT,
    "honorary_pallbearer" TEXT,
    "examiner_investigator" TEXT,
    "flag_receiver" TEXT,
    "deceased_identifier" TEXT,
    "hairdresser" TEXT,
    "embalming_authorizer" TEXT,
    "authorized_for_pickup" TEXT,
    "removed_implants_recipient" TEXT,
    "cremated_remains_mail_recipient" TEXT,
    "personal_property_recipient" TEXT,
    "deprecated_role" TEXT
);

CREATE INDEX "ix_case_people_index" ON "case_people" ("index");

CREATE TABLE IF NOT EXISTS "case_tasks" (
    "index" INTEGER,
    "id" TEXT,
    "kase_id" TEXT,
    "task_id" TEXT,
    "status" TEXT,
    "complete" TEXT,
    "notes" TEXT,
    "initials" TEXT
);

CREATE INDEX "ix_case_tasks_index" ON "case_tasks" ("index");

CREATE TABLE IF NOT EXISTS "dispositions" (
    "index" INTEGER,
    "id" TEXT,
    "disposition_method" TEXT,
    "place_id" TEXT,
    "kase_id" TEXT,
    "cremated_remains_present_for_service" TEXT,
    "cremains_mailed" TEXT,
    "is_headstone_desired" TEXT,
    "is_grave_unknown" TEXT,
    "cremation_place_id_klass" TEXT,
    "grave_owner_id_klass" TEXT,
    "cremation_director_id_klass" TEXT,
    "cremation_place_id" TEXT,
    "place_id_klass" TEXT,
    "notes" TEXT,
    "monument_notes" TEXT,
    "disposition_date" TEXT,
    "lot" TEXT,
    "plot" TEXT,
    "section" TEXT,
    "disc_number" TEXT,
    "cremation_date" TEXT,
    "remains_pickup_date" TEXT,
    "block" TEXT,
    "niche" TEXT,
    "cremation_permit_number" TEXT,
    "remains_back_by_date" TEXT,
    "container_description" TEXT,
    "secondary_container_description" TEXT,
    "mausoleum" TEXT,
    "grave_owner_id" TEXT,
    "cremation_time" TEXT,
    "cremation_tag_number" TEXT,
    "crypt" TEXT
);

CREATE INDEX "ix_dispositions_index" ON "dispositions" ("index");

CREATE TABLE IF NOT EXISTS "obituaries" (
    "index" INTEGER,
    "id" TEXT,
    "text" TEXT,
    "kase_id" TEXT,
    "draft_text" TEXT,
    "formatted_text" TEXT,
    "formatted_draft_text" TEXT
);

CREATE INDEX "ix_obituaries_index" ON "obituaries" ("index");

CREATE TABLE IF NOT EXISTS "preneeds" (
    "index" INTEGER,
    "id" TEXT,
    "kase_id" TEXT,
    "imminent" TEXT,
    "has_insurance" TEXT,
    "has_cemetery_property" TEXT,
    "has_trust" TEXT,
    "has_travel_plan" TEXT,
    "arrangement_type" TEXT,
    "referral_source" TEXT,
    "property_location" TEXT
);

CREATE INDEX "ix_preneeds_index" ON "preneeds" ("index");

CREATE TABLE IF NOT EXISTS "insurance_policies" (
    "index" INTEGER,
    "id" TEXT,
    "initial_face_value" TEXT,
    "insurance_company" TEXT,
    "preneed_id" TEXT,
    "established_at" TEXT,
    "assigned_to_payment" TEXT,
    "policy_transferred_to_id_klass" TEXT,
    "policy_number" TEXT,
    "current_face_value" TEXT,
    "age_at_purchase" TEXT
);

CREATE INDEX "ix_insurance_policies_index" ON "insurance_policies" ("index");

CREATE TABLE IF NOT EXISTS "trusts" (
    "index" INTEGER,
    "id" TEXT,
    "trust_company" TEXT,
    "preneed_id" TEXT
);

CREATE INDEX "ix_trusts_index" ON "trusts" ("index");

CREATE TABLE IF NOT EXISTS "veteran_infos" (
    "index" INTEGER,
    "id" TEXT,
    "deprecated_wars_fought" TEXT,
    "deprecated_military_rank" TEXT,
    "deprecated_military_branch" TEXT,
    "service_number" TEXT,
    "kase_id" TEXT,
    "deprecated_place_entered" TEXT,
    "deprecated_discharge_papers_received" TEXT,
    "is_flag" TEXT,
    "is_military_honors" TEXT,
    "is_requested_presence" TEXT,
    "marker" TEXT,
    "deprecated_date_entered" TEXT,
    "deprecated_date_discharged" TEXT,
    "honors_place_id_klass" TEXT,
    "deprecated_description" TEXT,
    "flag_instructions" TEXT,
    "deprecated_place_discharged" TEXT,
    "kase_id_klass" TEXT,
    "honors_place_id" TEXT,
    "va_number" TEXT,
    "honors_time" TEXT,
    "branch_presence_requested" TEXT,
    "air_force_cross" TEXT,
    "awards_received" TEXT,
    "bronze_star" TEXT,
    "dst_flying_cross" TEXT,
    "dst_service_cross" TEXT,
    "federal_forms_complete" TEXT,
    "general_info_complete" TEXT,
    "has_government_or_employer_burial_contribution" TEXT,
    "has_incurred_burial_expenses" TEXT,
    "has_incurred_expenses_for_remains_transportation" TEXT,
    "has_previously_received_allowance" TEXT,
    "headstone_info_complete" TEXT,
    "is_buried_in_national_cemetery" TEXT,
    "is_remains_not_buried" TEXT,
    "is_seeking_non_service_connected_benefits" TEXT,
    "is_selected_monument" TEXT,
    "is_service_connected_death" TEXT,
    "is_temporary_marker" TEXT,
    "medal_of_honor" TEXT,
    "navy_cross" TEXT,
    "purple_heart" TEXT,
    "service_records_complete" TEXT,
    "silver_star" TEXT,
    "military_organizations" TEXT,
    "incurred_expenses_for_remains_transportation_amount" TEXT,
    "xc_number" TEXT,
    "headstone_emblem" TEXT
);

CREATE INDEX "ix_veteran_infos_index" ON "veteran_infos" ("index");

CREATE TABLE IF NOT EXISTS "service_infos" (
    "index" INTEGER,
    "id" TEXT,
    "is_memorial_contributions" TEXT,
    "kase_id" TEXT,
    "has_pallbearers" TEXT,
    "has_stationery" TEXT,
    "folder_series" TEXT,
    "folder_quantity" TEXT,
    "folder_notes" TEXT,
    "acknowledgement_card_series" TEXT,
    "acknowledgement_card_quantity" TEXT,
    "register_book_series" TEXT,
    "has_photos" TEXT,
    "photos_received" TEXT,
    "photos_quantity" TEXT,
    "photos_returned_to_family" TEXT,
    "has_video" TEXT,
    "show_video_at_visitation" TEXT,
    "show_video_at_service" TEXT,
    "has_flowers" TEXT,
    "has_service_notes" TEXT,
    "florist_id_klass" TEXT,
    "register_book_notes" TEXT,
    "service_notes" TEXT,
    "flowers" TEXT,
    "flower_notes" TEXT,
    "memorial_card_series" TEXT,
    "memorial_card_quantity" TEXT,
    "memorial_card_notes" TEXT,
    "video_notes" TEXT,
    "florist_id" TEXT
);

CREATE INDEX "ix_service_infos_index" ON "service_infos" ("index");

CREATE TABLE IF NOT EXISTS "memorial_contributions" (
    "index" INTEGER,
    "id" TEXT,
    "place_id" TEXT,
    "service_info_id" TEXT
);

CREATE INDEX "ix_memorial_contributions_index" ON "memorial_contributions" ("index");

CREATE TABLE IF NOT EXISTS "inquiries" (
    "index" INTEGER,
    "id" TEXT,
    "contact_id" TEXT,
    "inquiry_type" TEXT,
    "archived_at" TEXT,
    "kase_id" TEXT,
    "remote_index" TEXT,
    "status" TEXT,
    "created_by_user_id_klass" TEXT,
    "location_id_klass" TEXT,
    "inquiry_staff_member_id_klass" TEXT,
    "location_id" TEXT,
    "created_by_user_id" TEXT,
    "inquiry_staff_member_id" TEXT,
    "kase_id_klass" TEXT,
    "contact_id_klass" TEXT
);

CREATE INDEX "ix_inquiries_index" ON "inquiries" ("index");

CREATE TABLE IF NOT EXISTS "rooms" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "place_id" TEXT
);

CREATE INDEX "ix_rooms_index" ON "rooms" ("index");

CREATE TABLE IF NOT EXISTS "events" (
    "index" INTEGER,
    "id" TEXT,
    "starts_at" TEXT,
    "duration" TEXT,
    "name" TEXT,
    "place_id" TEXT,
    "pending" TEXT,
    "location_id" TEXT,
    "event_type_name" TEXT,
    "export_to_frontrunner" TEXT,
    "export_to_funeral_tech" TEXT,
    "export_to_tco" TEXT,
    "uuid" TEXT,
    "kase_id_klass" TEXT,
    "room_id_klass" TEXT,
    "inquiry_id_klass" TEXT,
    "kase_id" TEXT,
    "family_arrival_time" TEXT,
    "place_id_klass" TEXT,
    "location_id_klass" TEXT,
    "notes" TEXT,
    "export_to_batesville" TEXT,
    "export_to_tukios" TEXT,
    "room_id" TEXT
);

CREATE INDEX "ix_events_index" ON "events" ("index");

CREATE TABLE IF NOT EXISTS "event_staff_members" (
    "index" INTEGER,
    "id" TEXT,
    "user_id" TEXT,
    "event_id" TEXT,
    "status" TEXT,
    "notified_by_id_klass" TEXT,
    "role" TEXT,
    "notified_at" TEXT,
    "notified_by_id" TEXT
);

CREATE INDEX "ix_event_staff_members_index" ON "event_staff_members" ("index");

CREATE TABLE IF NOT EXISTS "case_financials" (
    "index" INTEGER,
    "id" TEXT,
    "kase_id" TEXT,
    "merchandise_total" TEXT,
    "service_total" TEXT,
    "cash_advance_total" TEXT,
    "special_charge_total" TEXT,
    "taxable_total" TEXT,
    "package_discount" TEXT,
    "non_taxable_total" TEXT,
    "non_taxable_discount" TEXT,
    "discounts_total" TEXT,
    "sales_tax" TEXT,
    "special_tax" TEXT,
    "subtotal" TEXT,
    "total" TEXT,
    "payments_total" TEXT,
    "adjustments_total" TEXT,
    "balance" TEXT,
    "refunds_total" TEXT,
    "adjusted_tax" TEXT,
    "adjustments_without_tax" TEXT,
    "interests_total" TEXT,
    "payments_with_interests_total" TEXT
);

CREATE INDEX "ix_case_financials_index" ON "case_financials" ("index");

CREATE TABLE IF NOT EXISTS "selections" (
    "index" INTEGER,
    "id" TEXT,
    "required_purchase_reason" TEXT,
    "sfgs_last_generated" TEXT,
    "package_discount" TEXT,
    "logo_id" TEXT,
    "merchandise_total" TEXT,
    "service_total" TEXT,
    "cash_advance_total" TEXT,
    "special_charge_total" TEXT,
    "subtotal" TEXT,
    "total" TEXT,
    "sales_tax" TEXT,
    "special_tax" TEXT,
    "taxable_total" TEXT,
    "non_taxable_total" TEXT,
    "discounts_total" TEXT,
    "kase_financial_id" TEXT,
    "purchaser_id" TEXT,
    "payments_total" TEXT,
    "adjustments_total" TEXT,
    "balance" TEXT,
    "is_contract" TEXT,
    "posted" TEXT,
    "exported" TEXT,
    "name" TEXT,
    "purchaser_relationship" TEXT,
    "posted_at" TEXT,
    "exported_at" TEXT,
    "posted_by_id" TEXT,
    "exported_by_id" TEXT,
    "do_not_export" TEXT,
    "deprecated_type" TEXT,
    "gpl_locked" TEXT,
    "location_locked" TEXT,
    "refunds_total" TEXT,
    "overpayment_refunds_total" TEXT,
    "credit_refunds_total" TEXT,
    "non_tax_discounts_total" TEXT,
    "tax_discounts_total" TEXT,
    "has_unexported_accounting" TEXT,
    "export_started_at" TEXT,
    "merchandise_total_after_discounts" TEXT,
    "service_total_after_discounts" TEXT,
    "cash_advance_total_after_discounts" TEXT,
    "special_charge_total_after_discounts" TEXT,
    "taxable_total_after_discounts" TEXT,
    "non_taxable_total_after_discounts" TEXT,
    "subtotal_after_discounts" TEXT,
    "legacy_calculation_offset" TEXT,
    "adjusted_tax" TEXT,
    "adjustments_without_tax" TEXT,
    "contract_date" TEXT,
    "due_date" TEXT,
    "has_active_esign_contracts" TEXT,
    "interests_total" TEXT,
    "payments_with_interests_total" TEXT,
    "netsuite_item_receipt_ids" TEXT,
    "netsuite_purchase_order_ids" TEXT,
    "shipping_total" TEXT,
    "type" TEXT,
    "last_used_contract_template_id_klass" TEXT,
    "location_id_klass" TEXT,
    "staff_member_id_klass" TEXT,
    "unposted_by_id_klass" TEXT,
    "last_used_contract_template_id" TEXT,
    "exported_by_id_klass" TEXT,
    "logo_id_klass" TEXT,
    "posted_by_id_klass" TEXT,
    "purchaser_id_klass" TEXT,
    "statement_last_generated" TEXT,
    "unposted_at" TEXT,
    "unposted_by_id" TEXT,
    "location_id" TEXT,
    "staff_member_id" TEXT,
    "kase_id" TEXT,
    "kase_financial_id_klass" TEXT,
    "soa_note" TEXT,
    "contract_date_datetime_legacy" TEXT,
    "due_date_datetime_legacy" TEXT,
    "archived_at" TEXT,
    "last_unexported_by_id" TEXT,
    "last_unexported_at" TEXT,
    "custom_id" TEXT
);

CREATE INDEX "ix_selections_index" ON "selections" ("index");

CREATE TABLE IF NOT EXISTS "selection_products" (
    "index" INTEGER,
    "id" TEXT,
    "quantity" TEXT,
    "notes" TEXT,
    "selection_id" TEXT,
    "product_id" TEXT,
    "price" TEXT,
    "exported" TEXT,
    "exported_at" TEXT,
    "export_started_at" TEXT,
    "pull_from_inventory" TEXT
);

CREATE INDEX "ix_selection_products_index" ON "selection_products" ("index");

CREATE TABLE IF NOT EXISTS "selection_custom_products" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "quantity" TEXT,
    "is_taxed" TEXT,
    "selection_id" TEXT,
    "price" TEXT,
    "product_category_id" TEXT,
    "state_tax" TEXT,
    "local_tax" TEXT,
    "exported" TEXT,
    "cost" TEXT,
    "is_export_cogs" TEXT,
    "invoice_category_id_klass" TEXT,
    "statement_category_id_klass" TEXT,
    "statement_subcategory_id_klass" TEXT,
    "invoice_category_name" TEXT,
    "exported_at" TEXT,
    "export_started_at" TEXT,
    "notes" TEXT
);

CREATE INDEX "ix_selection_custom_products_index" ON "selection_custom_products" ("index");

CREATE TABLE IF NOT EXISTS "selection_packages" (
    "index" INTEGER,
    "id" TEXT,
    "pricing_amount" TEXT,
    "pricing_method" TEXT,
    "quantity" TEXT,
    "selection_id" TEXT,
    "package_id" TEXT,
    "discount" TEXT,
    "exported" TEXT,
    "total" TEXT,
    "exported_at" TEXT,
    "sub_total" TEXT,
    "export_started_at" TEXT
);

CREATE INDEX "ix_selection_packages_index" ON "selection_packages" ("index");

CREATE TABLE IF NOT EXISTS "selection_package_products" (
    "index" INTEGER,
    "selection_package_id" TEXT,
    "product_id" TEXT,
    "id" TEXT,
    "price" TEXT,
    "notes" TEXT
);

CREATE INDEX "ix_selection_package_products_index" ON "selection_package_products" ("index");

CREATE TABLE IF NOT EXISTS "payments" (
    "index" INTEGER,
    "id" TEXT,
    "amount" TEXT,
    "notes" TEXT,
    "payment_type_id" TEXT,
    "processor_pending" TEXT,
    "person_id" TEXT,
    "payer" TEXT,
    "collected_at" TEXT,
    "collected_by_id" TEXT,
    "exported" TEXT,
    "selection_id" TEXT,
    "exported_by_id" TEXT,
    "billing_address_id" TEXT,
    "exported_at" TEXT,
    "entered_by_id" TEXT,
    "export_started_at" TEXT,
    "marked_pending" TEXT,
    "payment_fee" TEXT,
    "effective_amount" TEXT,
    "uuid" TEXT,
    "general_payment_id_klass" TEXT,
    "insurance_policy_id_klass" TEXT,
    "approved_by_id_klass" TEXT,
    "person_id_klass" TEXT,
    "check_number" TEXT,
    "exported_by_id_klass" TEXT,
    "collected_by_id_klass" TEXT
);

CREATE INDEX "ix_payments_index" ON "payments" ("index");

CREATE TABLE IF NOT EXISTS "adjustments" (
    "index" INTEGER,
    "id" TEXT,
    "amount" TEXT,
    "notes" TEXT,
    "adjustment_type_id" TEXT,
    "collected_at" TEXT,
    "exported" TEXT,
    "selection_id" TEXT,
    "exported_by_id" TEXT,
    "exported_at" TEXT,
    "entered_by_id" TEXT,
    "adjusted_by_id" TEXT,
    "gain" TEXT,
    "export_started_at" TEXT,
    "include_item_tax" TEXT,
    "selection_product_id_klass" TEXT,
    "selection_custom_product_id_klass" TEXT,
    "selection_package_product_id_klass" TEXT,
    "line_item_account_id_klass" TEXT,
    "line_item_account_id" TEXT,
    "selection_product_id" TEXT,
    "adjustment_type_id_klass" TEXT,
    "selection_package_product_id" TEXT,
    "exported_by_id_klass" TEXT
);

CREATE INDEX "ix_adjustments_index" ON "adjustments" ("index");

CREATE TABLE IF NOT EXISTS "refunds" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "notes" TEXT,
    "amount" TEXT,
    "exported" TEXT,
    "exported_at" TEXT,
    "collected_at" TEXT,
    "entered_by_id" TEXT,
    "collected_by_id" TEXT,
    "exported_by_id" TEXT,
    "selection_id" TEXT,
    "export_started_at" TEXT,
    "uuid" TEXT,
    "person_id_klass" TEXT,
    "payment_id_klass" TEXT,
    "selection_custom_product_id_klass" TEXT,
    "selection_package_product_id_klass" TEXT,
    "selection_product_id_klass" TEXT,
    "person_id" TEXT,
    "refund_to" TEXT
);

CREATE INDEX "ix_refunds_index" ON "refunds" ("index");

CREATE TABLE IF NOT EXISTS "discounts" (
    "index" INTEGER,
    "id" TEXT,
    "name" TEXT,
    "amount" TEXT,
    "exported" TEXT,
    "collected_at" TEXT,
    "entered_by_id" TEXT,
    "collected_by_id" TEXT,
    "selection_id" TEXT,
    "discount_type_id" TEXT,
    "exported_by_id_klass" TEXT,
    "exported_at" TEXT,
    "export_started_at" TEXT,
    "exported_by_id" TEXT,
    "notes" TEXT,
    "collected_by_id_klass" TEXT
);

CREATE INDEX "ix_discounts_index" ON "discounts" ("index");

CREATE TABLE IF NOT EXISTS "contract_templates" (
    "index" INTEGER,
    "id" TEXT,
    "display_name" TEXT,
    "template_name" TEXT,
    "hide_discount" TEXT,
    "show_product_notes" TEXT,
    "show_date_of_service" TEXT,
    "show_cash_advance_verbiage" TEXT,
    "show_location" TEXT,
    "show_purchaser_ssn" TEXT,
    "show_funeral_director_license_number" TEXT,
    "created_by_user_id_klass" TEXT,
    "archived_by_user_id_klass" TEXT,
    "field_metadata.buyer-signature.display_name" TEXT,
    "field_metadata.buyer-signature.type" TEXT,
    "field_metadata.cosigned-signature.type" TEXT,
    "field_metadata.cosigned-signature.display_name" TEXT,
    "field_metadata.fh-signature.display_name" TEXT,
    "field_metadata.fh-signature.type" TEXT
);

CREATE INDEX "ix_contract_templates_index" ON "contract_templates" ("index");

CREATE TABLE IF NOT EXISTS "extract_dc" (
    "index" INTEGER,
    "branch_id" TEXT,
    "case_id" TEXT,
    "case_number" TEXT,
    "case_type" TEXT,
    "created_time" TEXT,
    "date_of_birth" TEXT,
    "date_of_death" TEXT,
    "time_of_death" TEXT,
    "assignee.email" TEXT,
    "fname" TEXT,
    "mname" TEXT,
    "lname" TEXT,
    "deathcertificate.about.gender" TEXT,
    "deathcertificate.about.ssn" TEXT,
    "deathcertificate.about.aka" TEXT,
    "deathcertificate.about.hasMemorialService" TEXT,
    "deathcertificate.life.birthPlace.city" TEXT,
    "deathcertificate.life.birthPlace.state" TEXT,
    "deathcertificate.life.birthPlace.country" TEXT,
    "deathcertificate.life.deathPlace.city" TEXT,
    "deathcertificate.life.deathPlace.state" TEXT,
    "deathcertificate.life.deathPlace.county" TEXT,
    "deathcertificate.life.deathPlace.country" TEXT,
    "deathcertificate.life.deathPlace.address1" TEXT,
    "deathcertificate.life.deathPlace.address2" TEXT,
    "deathcertificate.life.deathPlace.postalCode" TEXT,
    "deathcertificate.life.deathPlace.description" TEXT,
    "deathcertificate.life.deathPlace.locationName" TEXT,
    "deathcertificate.life.deathLocation" TEXT,
    "deathcertificate.life.physicianName" TEXT,
    "deathcertificate.life.physicianFaxNumber" TEXT,
    "deathcertificate.life.physicianPhoneNumber" TEXT,
    "deathcertificate.life.residencePlace.city" TEXT,
    "deathcertificate.life.residencePlace.state" TEXT,
    "deathcertificate.life.residencePlace.county" TEXT,
    "deathcertificate.life.residencePlace.country" TEXT,
    "deathcertificate.life.residencePlace.address1" TEXT,
    "deathcertificate.life.residencePlace.address2" TEXT,
    "deathcertificate.life.residencePlace.postalCode" TEXT,
    "deathcertificate.life.residencePlace.description" TEXT,
    "deathcertificate.life.residencePlace.locationName" TEXT,
    "deathcertificate.life.residencePlace.unknown" TEXT,
    "deathcertificate.life.residencePlace.filingState" TEXT,
    "deathcertificate.life.residencePlace.yearsInCounty" TEXT,
    "deathcertificate.life.residencePlace.insideCityLimits" TEXT,
    "raw_race" TEXT,
    "deathcertificate.race.ancestry" TEXT,
    "deathcertificate.race.hispanicOrigin" TEXT,
    "deathcertificate.race.isUsCitizen" TEXT,
    "deathcertificate.race.race_specify_asian" TEXT,
    "deathcertificate.race.race_specify_other" TEXT,
    "deathcertificate.race.race_specify_islander" TEXT,
    "deathcertificate.race.race_specify_indian_tribe" TEXT,
    "deathcertificate.race.hispanicOrigin_specify_other" TEXT,
    "deathcertificate.parents.fatherBirthPlace.city" TEXT,
    "deathcertificate.parents.fatherBirthPlace.state" TEXT,
    "deathcertificate.parents.fatherBirthPlace.country" TEXT,
    "deathcertificate.parents.fatherBirthPlace.unknown" TEXT,
    "deathcertificate.parents.fatherBirthPlace.description" TEXT,
    "deathcertificate.parents.motherBirthPlace.city" TEXT,
    "deathcertificate.parents.motherBirthPlace.state" TEXT,
    "deathcertificate.parents.motherBirthPlace.country" TEXT,
    "deathcertificate.parents.motherBirthPlace.unknown" TEXT,
    "deathcertificate.parents.motherBirthPlace.description" TEXT,
    "deathcertificate.parents.motherName.unknown" TEXT,
    "deathcertificate.parents.motherName.maidenName" TEXT,
    "deathcertificate.marriage.marriageDate" TEXT,
    "deathcertificate.marriage.marriageDate_unknown" TEXT,
    "deathcertificate.marriage.maritalStatus" TEXT,
    "deathcertificate.marriage.marriagePlace.city" TEXT,
    "deathcertificate.marriage.marriagePlace.state" TEXT,
    "deathcertificate.marriage.marriagePlace.country" TEXT,
    "deathcertificate.marriage.marriagePlace.unknown" TEXT,
    "deathcertificate.marriage.marriagePlace.description" TEXT,
    "deathcertificate.marriage.spouseMaidenName" TEXT,
    "deathcertificate.military.military" TEXT,
    "deathcertificate.military.militaryBranch" TEXT,
    "deathcertificate.military.militaryRank" TEXT,
    "SrvcEnteredYear" TEXT,
    "SrvcReleasedYear" TEXT,
    "deathcertificate.military.militaryHonors" TEXT,
    "deathcertificate.military.militaryServiceNumber" TEXT,
    "deathcertificate.military.disabilityContributedToDeath" TEXT,
    "deathcertificate.education.educationListOfOptions" TEXT,
    "deathcertificate.education.educationHistory" TEXT,
    "deathcertificate.workHistory.retiredInYear" TEXT,
    "deathcertificate.workHistory.currentEmployer" TEXT,
    "deathcertificate.workHistory.normalOccupation" TEXT,
    "deathcertificate.workHistory.retiredLastEmployer" TEXT,
    "deathcertificate.workHistory.occupationListOfOptions" TEXT,
    "deathcertificate.workHistory.normalOccupationIndustry" TEXT,
    "deathcertificate.workHistory.normalOccupation_unknown" TEXT,
    "deathcertificate.workHistory.normalOccupationIndustry_unknown" TEXT,
    "deathcertificate.restingPlace.options" TEXT,
    "deathcertificate.restingPlace.specifyOther" TEXT,
    "deathcertificate.restingPlace.dispositionDate" TEXT,
    "deathcertificate.restingPlace.cemeteryPropertyDetails" TEXT,
    "deathcertificate.restingPlace.ownsCemeteryProperty" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.city" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.state" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.county" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.country" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.address1" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.address2" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.postalCode" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.description" TEXT,
    "deathcertificate.restingPlace.dispositionPlace.locationName" TEXT,
    "case_note" TEXT
);

CREATE INDEX "ix_extract_dc_index" ON "extract_dc" ("index");

CREATE TABLE IF NOT EXISTS "extract_help" (
    "index" INTEGER,
    "branch_id" TEXT,
    "case_id" TEXT,
    "case_number" TEXT,
    "fname" TEXT,
    "mname" TEXT,
    "lname" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "raw_relationship" TEXT,
    "address1" TEXT,
    "address2" TEXT,
    "city" TEXT,
    "state" TEXT,
    "country" TEXT,
    "postal_code" TEXT,
    "is_informant" TEXT,
    "is_deceased" TEXT
);

CREATE INDEX "ix_extract_help_index" ON "extract_help" ("index");

CREATE TABLE IF NOT EXISTS "extract_finance" (
    "index" INTEGER,
    "case_number" TEXT,
    "contract_date" TEXT,
    "funeral_home" TEXT,
    "decedent" TEXT,
    "director" TEXT,
    "date_of_death" TEXT,
    "transaction_date" TEXT,
    "group" TEXT,
    "description" TEXT,
    "type" TEXT,
    "quantity" TEXT,
    "price" TEXT,
    "total" TEXT
);

CREATE INDEX "ix_extract_finance_index" ON "extract_finance" ("index");